source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target :'Weaver' do
 # pod 'Texture', :git => 'git@github.com:TextureGroup/Texture.git', :branch => 'MSTesting'
  # pod 'Texture/Video', :git => 'git@github.com:TextureGroup/Texture.git', :branch => 'MSTesting'
  pod 'Texture', :path => '../../Texture'
  pod 'SocketRocket', :inhibit_warnings => true
end
